In [4]:
import pandas

In [6]:
df=pandas.read_csv("./example.csv")
df

           Continent          Country
0             Europe   United Kingdom
1             Europe           Russia
2             Europe            Italy
3             Europe           France
4             Europe          Belgium
5             Europe          Denmark
6             Europe           Sweden
7             Europe          Estonia
8             Europe           Greece
9             Europe           Latvia
10            Europe      Switzerland
11            Europe           Poland
12            Europe        Lithuania
13            Europe          Hungary
14            Europe          Romania
15            Europe            Spain
16            Europe          Germany
17            Europe          Finland
18            Europe           Norway
19            Europe          Ireland
20            Europe         Slovakia
21            Europe         Portugal
22            Europe          Austria
23            Europe          Iceland
24            Europe         Bulgaria
25            Europe          Croatia
26            Europe          Ukraine
27            Europe   Czech Republic
28            Europe          Albania
29            Europe          Belarus
..               ...              ...
164           Africa             Mali
165           Africa       Mauritania
166           Africa          Morocco
167           Africa       Mozambique
168           Africa          Namibia
169           Africa            Niger
170           Africa          Nigeria
171           Africa           Rwanda
172           Africa          Senegal
173           Africa       Seychelles
174           Africa     Sierra Leone
175           Africa          Somalia
176           Africa        Swaziland
177           Africa         Tanzania
178           Africa             Togo
179           Africa          Tunisia
180           Africa           Uganda
181           Africa   Western Sahara
182           Africa           Zambia
183           Africa         Zimbabwe
184           Africa        Mauritius
185           Africa      South Sudan
186           Africa         Lanseria
187  Oceans and Seas         Atlantic
188  Oceans and Seas          Pacific
189  Oceans and Seas           Arctic
190  Oceans and Seas         Southern
191  Oceans and Seas           Indian
192  Oceans and Seas    Mediterranean
193  Oceans and Seas        Caribbean

[194 rows x 2 columns]